angular_range: 50
batch_norm: true
batch_size: 6
data_generation_methods:
- phantom_1
- phantom_2
- phantom_3
- phantom_4
data_generation_probability:
- 2
- 2.25
- 3
- 1
internal_ch: 64
kernel_size: 3
lr: 0.0001
n_dual: 2
n_iter: 4
n_layer: 4
n_primal: 4
normalize_sinogram: true
num_epochs_full: 250
rel_noise: 0.01
train_size: 1000
use_sigmoid: false
val_size: 64
